export const GET_CLIENTS = 'GET_CLIENTS';
export const LOAD_CLIENTS = 'LOAD_CLIENTS';
export const LOAD_CLIENTS_SUCCESS = 'LOAD_CLIENTS_SUCCESS';
export const LOAD_CLIENTS_ERROR = 'LOAD_CLIENTS_ERROR';
export const START_REMOVE_SELECTED_CLIENTS_FROM_LIST = 'START_REMOVE_SELECTED_CLIENTS_FROM_LIST';
export const REMOVE_SELECTED_CLIENTS_FROM_LIST_SUCCESS = 'REMOVE_SELECTED_CLIENTS_FROM_LIST_SUCCESS';
export const REMOVE_SELECTED_CLIENTS_FROM_LIST_ERROR = 'REMOVE_SELECTED_CLIENTS_FROM_LIST_ERROR';
export const RESET_CLIENTS = 'RESET_CLIENTS';
