export const LOAD_LEVELS = 'LOAD_LEVELS';
export const LOAD_LEVELS_SUCCESS = 'LOAD_LEVELS_SUCCESS';
export const LOAD_LEVELS_ERROR = 'LOAD_LEVELS_ERROR';
export const SENDING_QUIZ = 'SENDING_QUIZ';
export const SEND_QUIZ_SUCCESS = 'SEND_QUIZ_SUCCESS';
export const SEND_QUIZ_ERROR = 'SEND_QUIZ_ERROR';
