export const GET_STUDENTS = 'GET_STUDENTS';
export const LOAD_STUDENTS = 'LOAD_STUDENTS';
export const LOAD_STUDENTS_SUCCESS = 'LOAD_STUDENTS_SUCCESS';
export const LOAD_STUDENTS_ERROR = 'LOAD_STUDENTS_ERROR';
